version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barrier-api
    depends_on:
      - db
      - redis
      - kafka
    environment:
      # Настройки подключения к PostgreSQL
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: barrier_db
      DB_USER: barrier_user
      DB_PASSWORD: barrier_password

      # Настройки Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"

      # Настройки Kafka для логирующей миддлвари
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_LOG_TOPIC: http_logs

      # APP_ENV: "development"
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: barrier-postgres
    environment:
      POSTGRES_DB: barrier_db
      POSTGRES_USER: barrier_user
      POSTGRES_PASSWORD: barrier_password
    ports:
      - "5432:5432"
    volumes:
      - barrier_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: barrier-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: barrier-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: barrier-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      # Дополнительный наружный порт для клиентов на хосте (если нужен)
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: barrier-zookeeper:2181
      # Внутренний адрес для других контейнеров
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://barrier-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

volumes:
  barrier_pg_data: